### ISSUE TITLE
More undervolt on gpu

### ISSUE THREAD

**Issue by vatva691** [lyq1996/msm8998_offset_voltage#1]
I'm using google pixel 2 xl and its run msm8998, i have test -100mv cpu and -230mv gpu and it play game fine, but there is anyway to undervolt gpu more to its more save battery?

**Comment by lyq1996** [comment]
> I'm using google pixel 2 xl and its run msm8998, i have test -100mv cpu and -230mv gpu and it play game fine, but there is anyway to undervolt gpu more to its more save battery?

Yes, you can.

Just flash the zip using twrp again, it will continue undervolt on your current volt.
